export const VALIDATION_ERROR = `Request didn't pass validation`;
export const PERMISSION_DENIED = 'Permission Denied';
export const SOMETHING_WENT_WRONG = 'Something went wrong, please try again';
export const REQUIRED = resource => `${resource} is required`;
export const INVALID = resource => `${resource} is invalid`;
export const ALREADY_EXISTS = resource => `${resource} already exists!`;
export const NOT_EXISTS = resource => `${resource} doesn't exist!`;
export const INVALID_EMAIL_OR_PASSWORD = 'Invalid email or password';
export const SERVICE_UNAVAILABLE = 'Service is temporarily unavailable';
export const CRON_TIMEZONE = 'Asia/Yerevan';
export const CRON_TIME = '*/5 * * * *';
